Repository NCAR/aerosol-workshop-driver, pull requests merged in 2022-04, with the labels that each got.

#14 Added a missing return statement. This fixes array test failures.
  src/array/array.c
Labels: bug fix

#16 Develop 15 mac tests
  .github/workflows/test-macos.yml
  .github/workflows/test.yml
  include/aero/array/c_array.hpp
  include/aero/array/fortran_array.hpp
  my_model/template/c/my_model.c
Labels: testing

#40 Filled out the README.
  README.md
Labels: documentation

#45 Fixes missing headers for printf calls.
  my_model/template/c/my_model.c
  my_model/template/cpp/my_model.cpp
  src/array/c_array.F90
  src/array/cpp_array.F90
Labels: bug fix
